name: setup
description: setup
inputs:
  github_app_token:
    description: 'GitHub Access Token'
    required: true

  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  ssh_key:
    description: 'SSH Key for Terraform Private Module'
    required: false
outputs:
  working_directory:
    description: working directory
    value: ${{ steps.target-config.outputs.working_directory }}
  s3_bucket_name_plan_file:
    description: S3 Bucket name for plan files
    value: ${{ steps.target-config.outputs.s3_bucket_name_plan_file}}
  s3_bucket_name_tfmigrate_history:
    description: S3 Bucket name for tfmigrate history files
    value: ${{ steps.target-config.outputs.s3_bucket_name_tfmigrate_history}}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-target-config@main
      id: target-config

    - run: aqua i -l -a
      shell: bash
      working-directory: ${{ steps.target-config.outputs.working_directory }}

    - uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
      if: steps.target-config.outputs.aws_assume_role_arn != ''
      with:
        role-to-assume: ${{ steps.target-config.outputs.aws_assume_role_arn }}
        role-session-name: samplerolesession
        aws-region: ${{ steps.target-config.outputs.aws_region }}

    - uses: suzuki-shunsuke/tfaction/export-aws-secrets-manager@main

    - uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # v1.0.0
      if: steps.target-config.outputs.gcp_service_account != ''
      with:
        workload_identity_provider: ${{ steps.target-config.outputs.gcp_workload_identity_provider }}
        service_account: ${{ steps.target-config.outputs.gcp_service_account }}

    - uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587 # v1.1.0
      if: steps.target-config.outputs.gcp_service_account != ''

    - uses: suzuki-shunsuke/tfaction/deploy-ssh-key@main
      if: inputs.ssh_key != ''
      with:
       ssh_key: ${{ inputs.ssh_key }}
