name: set-drift-env
description: Set environment variables for drift detection
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-global-config@main
      id: global-config
    - run: |
        echo "TFCMT_REPO_OWNER=$REPO_OWNER" >> "$GITHUB_ENV"
        echo "TFCMT_REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"
        echo "TFCMT_PR_NUMBER=$TFACTION_DRIFT_ISSUE_NUMBER" >> "$GITHUB_ENV"

        echo "GH_COMMENT_REPO_OWNER=$REPO_OWNER" >> "$GITHUB_ENV"
        echo "GH_COMMENT_REPO_NAME=$REPO_NAME" >> "$GITHUB_ENV"
        echo "GH_COMMENT_PR_NUMBER=$TFACTION_DRIFT_ISSUE_NUMBER" >> "$GITHUB_ENV"

      shell: bash
      env:
        REPO_OWNER: ${{steps.global-config.outputs.drift_issue_repo_owner}}
        REPO_NAME: ${{steps.global-config.outputs.drift_issue_repo_name}}
