name: update-drift-issue-after-apply
description: Update a drift issue after apply
inputs:
  github_token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}

  job_status:
    description: Job status
    required: true

  issue_number:
    description: Drift issue number
    required: true

  issue_state:
    description: Drift issue state
    required: true

  drift_commented:
    description: Whether a comment is posted to the drift issue
    required: true
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-global-config@main
      id: global-config

    - name: Close an issue
      shell: bash
      if: |
        inputs.job_status == 'success' && inputs.issue_state == 'open'
      env:
        GITHUB_TOKEN: ${{inputs.github_token}}
        REPO: ${{steps.global-config.outputs.drift_issue_repo_owner}}/${{steps.global-config.outputs.drift_issue_repo_name}}
        NUMBER: ${{inputs.number}}
      run: |
        gh issue close \
          --repo "$REPO" \
          "$NUMBER"

    - name: Reopen an issue
      shell: bash
      if: |
        inputs.job_status != 'success' && inputs.issue_state == 'closed'
      env:
        GITHUB_TOKEN: ${{inputs.github_token}}
        NUMBER: ${{inputs.number}}
        REPO: ${{steps.global-config.outputs.drift_issue_repo_owner}}/${{steps.global-config.outputs.drift_issue_repo_name}}
      run: |
        gh issue reopen \
          --repo "$REPO" \
          "$NUMBER"

    - name: Post a comment
      shell: bash
      if: "inputs.drift_commented != 'true'"
      env:
        GITHUB_TOKEN: ${{inputs.github_token}}
        ISSUE_REPO_OWNER: ${{steps.global-config.outputs.drift_issue_repo_owner}}
        ISSUE_REPO_NAME: ${{steps.global-config.outputs.drift_issue_repo_name}}
        JOB_STATUS: ${{inputs.job_status}}
        NUMBER: ${{inputs.issue_number}}
      run: |
        github-comment post \
          -c "$GITUB_ACTION_PATH/github-comment.yaml" \
          -k post-apply \
          -org "$ISSUE_REPO_OWNER" \
          -repo "$ISSUE_REPO_NAME" \
          -pr "${NUMBER:-$NEW_ISSUE_NUMBER}" \
          -var "pr_url:$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$CI_INFO_PR_NUMBER" \
          -var "job_status:$JOB_STATUS"
