name: update-drift-issue-after-apply
description: Update a drift issue after apply
inputs:
  github_app_token:
    description: 'GitHub Access Token'
    required: true

  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Find an issue
      shell: bash
      id: issue
      env:
        GITHUB_TOKEN: ${{inputs.github_token}}
        REPO: ""
      run: |
        gh search issues \
          --json state,number \
          -L 1 \
          --repo "$REPO" \
          --label terraform-drift \
          --match title "Terraform Drift ($TFACTION_TARGET)" > issues.json
        cat issues.json
        length=$(jq length < issues.json)
        echo "length=$length" >> "$GITHUB_OUTPUT"
        if [ 1 -eq "$length" ]; then
          echo state=$(jq -r ".[0].state" < issues.json) >> "$GITHUB_OUTPUT"
          echo number=$(jq -r ".[0].number" < issues.json) >> "$GITHUB_OUTPUT"
        fi

    - uses: suzuki-shunsuke/tfaction/update-drift-issue@main
