name: terraform apply
description: terraform apply
inputs:
  github_app_token:
    description: 'GitHub Access Token'
    required: true

  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}

outputs:
  drift_commented:
    description: whether a comment is posted to the drift issue
    value: ${{ steps.apply.outputs.drift_commented }}

runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-target-config@main
      id: target-config
    - uses: suzuki-shunsuke/tfaction/get-global-config@main
      id: global-config
    - uses: suzuki-shunsuke/tfaction/check-terraform-skip@main
      id: check-terraform-skip
      with:
        labels: ${{ env.CI_INFO_TEMP_DIR }}/labels.txt
        pr_author: ${{ env.CI_INFO_PR_AUTHOR }}
        skip_label_prefix: ${{ steps.global-config.outputs.label_prefix_skip }}

    - run: |
        if tfaction -v >/dev/null 2>&1; then
          tfaction get-or-create-drift-issue
        fi
      id: drift-issue
      shell: bash
      if: "!fromJSON(steps.check-terraform-skip.outputs.skip_terraform)"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - run: bash ${{ github.action_path }}/main.sh
      id: apply
      working-directory: ${{ steps.target-config.outputs.working_directory }}
      shell: bash
      if: "!fromJSON(steps.check-terraform-skip.outputs.skip_terraform)"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_APP_TOKEN: ${{ inputs.github_app_token }}
        S3_BUCKET_NAME_PLAN_FILE: ${{ steps.target-config.outputs.s3_bucket_name_plan_file }}
        GCS_BUCKET_NAME_PLAN_FILE: ${{ steps.target-config.outputs.gcs_bucket_name_plan_file }}
        DRIFT_ISSUE_NUMBER: ${{ steps.drift-issue.outputs.issue_number }}
        DRIFT_ISSUE_REPO_OWNER: ${{steps.global-config.outputs.drift_issue_repo_owner}}
        DRIFT_ISSUE_REPO_NAME: ${{steps.global-config.outputs.drift_issue_repo_name}}
