name: detect-drift
description: Detect Terraform drift
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  issue_number:
    description: 'GitHub Issue number'
    required: true
  issue_state:
    description: 'GitHub Issue state'
    required: true
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-global-config@main
      id: global-config
    - uses: suzuki-shunsuke/tfaction/setup-base@main
      id: setup-base
      env:
        TFACTION_JOB_TYPE: terraform

    - shell: bash
      working-directory: ${{steps.setup-base.outputs.working_directory}}
      env:
        ISSUE_REPO_OWNER: ${{steps.global-config.outputs.drift_issue_repo_owner}}
        ISSUE_REPO_NAME: ${{steps.global-config.outputs.drift_issue_repo_name}}
        ISSUE_NUMBER: ${{inputs.issue_number}}
      run: |
        github-comment exec \
          -org "$ISSUE_REPO_OWNER" \
          -repo "$ISSUE_REPO_NAME" \
          -pr "$ISSUE_NUMBER" \
          -- \
          terraform init -input=false

    - run: bash ${{github.action_path}}/plan.sh
      shell: bash
      env:
        ISSUE_REPO_OWNER: ${{steps.global-config.outputs.drift_issue_repo_owner}}
        ISSUE_REPO_NAME: ${{steps.global-config.outputs.drift_issue_repo_name}}
        ISSUE_NUMBER: ${{inputs.issue_number}}
        ISSUE_STATE: ${{inputs.issue_state}}
