name: detect-drift
description: Detect Terraform drift
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  issue_owner:
    description: 'GitHub Issue Owner'
    required: true
  issue_repo:
    description: 'GitHub Issue Repository name'
    required: true
  issue_number:
    description: 'GitHub Issue number'
    required: true
runs:
  using: composite
  env:
    ISSUE_OWNER: ${{inputs.issue_owner}}
    ISSUE_REPO: ${{inputs.issue_repo}}
    ISSUE_NUMBER: ${{inputs.issue_number}}
  steps:
    - uses: suzuki-shunsuke/tfaction/setup-base@main
      id: setup-base

    - shell: bash
      working-directory: ${{steps.setup-base.outputs.working_directory}}
      env:
        REPO: ${{steps.global-config.outputs.drift_issue_repo}}
      run: |
        github-comment exec \
          -org "$ISSUE_OWNER" \
          -repo "$ISSUE_NUMBER" \
          -pr "$ISSUE_NUMBER" \
          -- \
          terraform init -input=false

    - run: bash ${{github.action_path}}/plan.sh
      id: plan
      shell: bash
