name: detect-drift-issue
description: Detect Terraform drift issue
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
outputs:
  issue_number:
    description: GitHub Issue number
    value: ${{ steps.issue.outputs.number }}
  issue_number:
    description: GitHub Issue number
    value: ${{ steps.issue.outputs.state }}

runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-global-config@main
      id: global-config
    - name: Find an issue
      shell: bash
      id: issue
      env:
        GITHUB_TOKEN: ${{inputs.github_token}}
        REPO: ${{steps.global-config.outputs.drift_issue_repo_owner}}/${{steps.global-config.outputs.drift_issue_repo_name}}
      run: bash ${{github.action_path}}/find_issue.sh
