name: Synchronize drift issue description

on: workflow_call

jobs:
  sync-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh -R "$GITHUB_REPOSITORY" issue edit "${{github.event.issue.number}}" -b "$BODY"
        env:
          GITHUB_TOKEN: ${{github.token}}
          BODY: |
            This issus was created by [tfaction](https://suzuki-shunsuke.github.io/tfaction/docs/).

            About this issue, please see [the document](https://suzuki-shunsuke.github.io/tfaction/docs/feature/drift-detection).

            ## Latest comment

            [${{github.event.comment.created_at}}](${{github.event.comment.html_url}})

            ${{github.event.comment.body}}
